language: node_js
sudo: true
node_js:
  - "8"
addons:
  firefox: "latest"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - npm install -g codecov
  - npm install -g cross-env
  - npm install -g nyc
  - npm install
script:
  - npm run test
  - npm run test:e2e
  - npm run lint
  - npm run coverage
  - travis wait npm run build
  - cat ./coverage/lcov.info | codecov

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
